### ISSUE TITLE
Error in the documentation upload_build instead of build_upload 

### ISSUE THREAD

**Issue by xNok** [emerald-squad/artifactory-resource#12]
**Describe the bug**

In the documentation the params is called `upload_build`.

```
- put: my-artifact
  params:
    path: artifacts
    upload_build: true
    build_publish:
      build_name: wonderful-artifact-build
      git_url: <GIT URL>
      git_rev: artifacts/revision
      env_include: "BUILD|ATC"
      env_exclude: "API_KEY"
```

In the code it is called `build_upload `

```
build_upload=$(jq -r '.params.build_upload // empty' < ${payload})
```
